2025-02-28 09:22:55.112 UTC [1] LOG:  server process (PID 494) exited with exit code 255
2025-02-28 09:22:55.112 UTC [1] LOG:  terminating any other active server processes
2025-02-28 09:22:55.155 UTC [1] LOG:  all server processes terminated; reinitializing
2025-02-28 09:22:55.264 UTC [497] LOG:  database system was interrupted; last known up at 2025-02-28 09:22:44 UTC
2025-02-28 09:23:12.534 UTC [497] LOG:  syncing data directory (fsync), elapsed time: 10.00 s, current path: ./base/5/6117
2025-02-28 09:23:13.911 UTC [497] LOG:  database system was not properly shut down; automatic recovery in progress
2025-02-28 09:23:14.074 UTC [497] LOG:  redo starts at 0/C0001E0
2025-02-28 09:23:14.076 UTC [497] LOG:  invalid record length at 0/C000218: expected at least 24, got 0
2025-02-28 09:23:14.076 UTC [497] LOG:  redo done at 0/C0001E0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-02-28 09:23:14.245 UTC [498] LOG:  checkpoint starting: end-of-recovery immediate wait
2025-02-28 09:23:14.409 UTC [498] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.038 s, sync=0.025 s, total=0.177 s; sync files=2, longest=0.013 s, average=0.013 s; distance=0 kB, estimate=0 kB; lsn=0/C000218, redo lsn=0/C000218
2025-02-28 09:23:14.433 UTC [1] LOG:  database system is ready to accept connections
2025-02-28 09:23:23.989 UTC [498] LOG:  checkpoint starting: force wait
2025-02-28 09:23:24.694 UTC [498] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.019 s, sync=0.001 s, total=0.705 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16383 kB, estimate=16383 kB; lsn=0/D000080, redo lsn=0/D000028
2025-02-28 09:24:15.189 UTC [1] LOG:  server process (PID 522) exited with exit code 255
2025-02-28 09:24:15.189 UTC [1] LOG:  terminating any other active server processes
2025-02-28 09:24:15.252 UTC [1] LOG:  all server processes terminated; reinitializing
2025-02-28 09:24:15.342 UTC [525] LOG:  database system was interrupted; last known up at 2025-02-28 09:23:24 UTC
2025-02-28 09:24:20.513 UTC [1] LOG:  issuing SIGKILL to recalcitrant children
2025-02-28 09:24:25.651 UTC [1] LOG:  issuing SIGKILL to recalcitrant children
2025-02-28 09:24:25.652 UTC [1] LOG:  all server processes terminated; reinitializing
2025-02-28 09:24:25.730 UTC [530] LOG:  database system was interrupted; last known up at 2025-02-28 09:23:24 UTC
2025-02-28 09:24:42.618 UTC [530] LOG:  syncing data directory (fsync), elapsed time: 10.00 s, current path: ./base/5/4154
2025-02-28 09:24:44.309 UTC [530] LOG:  database system was not properly shut down; automatic recovery in progress
2025-02-28 09:24:44.648 UTC [530] LOG:  redo starts at 0/D000028
2025-02-28 09:24:44.652 UTC [530] LOG:  invalid record length at 0/D000130: expected at least 24, got 0
2025-02-28 09:24:44.652 UTC [530] LOG:  redo done at 0/D0000F8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-02-28 09:24:44.877 UTC [531] LOG:  checkpoint starting: end-of-recovery immediate wait
2025-02-28 09:24:45.070 UTC [531] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.053 s, sync=0.028 s, total=0.217 s; sync files=2, longest=0.015 s, average=0.014 s; distance=0 kB, estimate=0 kB; lsn=0/D000130, redo lsn=0/D000130
2025-02-28 09:24:45.106 UTC [1] LOG:  database system is ready to accept connections



root@ubuntu:/etc/pgbackrest# pgbackrest --stanza=pg-container stanza-create
root@ubuntu:/etc/pgbackrest# pgbackrest --stanza=pg-container backup
2025-02-28 01:24:06.460 P00   WARN: no prior backup exists, incr backup has been changed to full
2025-02-28 01:24:13.885 P00   WARN: resumable backup 20250228-012042F of same type exists -- invalid files will be removed then the backup will resume
2025-02-28 01:24:58.934 P00  ERROR: [057]: raised from remote-0 ssh protocol on 'pg-container': unable to execute query 'select pg_catalog.pg_is_in_recovery()': server closed the connection unexpectedly
                                    	This probably means the server terminated abnormally
                                    	before or while processing the request.
                                    invalid socket
root@ubuntu:/etc/pgbackrest# 

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# Backup server 
cat /etc/pgbackrest/pgbackrest.conf
[global]
repo1-path=/var/lib/pgbackrest-1
repo1-retention-full=2
repo1-type=posix

[pg-container]
pg1-host=pg-container
pg1-port=5432
pg1-user=postgres
pg1-database=test_db
pg1-path=/var/lib/postgresql/data


# Remote server
cat /etc/pgbackrest/pgbackrest.conf
[global]
repo1-host=192.168.68.160
repo1-host-user=postgres

[pg-container]
pg1-path=/var/lib/postgresql/data


wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=pg-container archive-push %p'
max_wal_senders = 3
wal_keep_size = 256MB
archive_timeout = 900
listen_addresses = '*'



\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# Achival Errors

sudo chown -R postgres:postgres /var/lib/pgbackrest-1
sudo chmod -R 750 /var/lib/pgbackrest-1

sudo -i -u postgres
sudo -u postgres ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
sudo -u postgres ssh-copy-id postgres@10.210.4.213 -p 222


